# Generated by Django 5.2 on 2026-03-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuwoo_api', '0004_add_geolocation_and_service_request_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_provider_profile',
            field=models.BooleanField(default=False),
        ),
    ]
