# Generated by Django 5.2 on 2026-03-10 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuwoo_api', '0006_customuser_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant payé par le client ($)', max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=4, help_text='Taux de commission appliqué (ex: 0.15)', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Commission Fuwoo ($)', max_digits=10)),
                ('provider_amount', models.DecimalField(decimal_places=2, help_text='Montant reversé au prestataire ($)', max_digits=10)),
                ('stripe_session_id', models.CharField(blank=True, max_length=300, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='fuwoo_api.bid')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
