# Generated by Django 5.2 on 2026-03-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuwoo_api', '0007_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='identity_docs/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='identity_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='identity_status',
            field=models.CharField(choices=[('not_submitted', 'Non soumis'), ('pending', 'En attente de révision'), ('verified', 'Vérifié'), ('rejected', 'Rejeté')], default='not_submitted', max_length=20),
        ),
    ]
