# Generated by Django 5.2 on 2026-03-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuwoo_api', '0009_portfoliophoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=60, help_text='Durée estimée en minutes'),
        ),
        migrations.AlterField(
            model_name='service',
            name='max_distance',
            field=models.IntegerField(default=100, help_text='Distance max en km'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_unit',
            field=models.CharField(blank=True, default='soumission', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_area',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
