# Generated by Django 5.2 on 2026-03-16 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuwoo_api', '0011_servicerequest_address_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('pipeline_stage', models.CharField(choices=[('lead', 'Lead'), ('contacted', 'Contacté'), ('quoted', 'Soumission envoyée'), ('active', 'Client actif'), ('recurring', 'Récurrent'), ('inactive', 'Inactif')], default='lead', max_length=20)),
                ('source', models.CharField(choices=[('bid', 'Offre acceptée'), ('manual', 'Ajout manuel')], default='manual', max_length=10)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('service_count', models.IntegerField(default=0)),
                ('reminder_date', models.DateField(blank=True, null=True)),
                ('reminder_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_clients', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('crm_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='fuwoo_api.crmclient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMServiceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_link', to='fuwoo_api.bid')),
                ('crm_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='fuwoo_api.crmclient')),
            ],
        ),
    ]
