# Generated by Django 5.2 on 2026-03-16 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuwoo_api', '0012_crm_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='fuwoo_api.bid'),
        ),
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fuwoo_api.booking'),
        ),
        migrations.AlterField(
            model_name='review',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fuwoo_api.service'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('open', 'Ouverte'), ('awarded', 'Attribuée'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='open', max_length=20),
        ),
    ]
