# Generated by Django 5.2 on 2026-03-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuwoo_api', '0013_review_bid_alter_review_booking_alter_review_service_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', False)), fields=('booking', 'client'), name='unique_review_per_booking_client'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('bid__isnull', False)), fields=('bid', 'client'), name='unique_review_per_bid_client'),
        ),
    ]
