# Generated by Django 5.2 on 2026-03-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuwoo_api', '0014_review_unique_bid_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cnesst_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
